### ISSUE TITLE
show the api info Error

### ISSUE THREAD

**Issue by Blockchain-Key** [NonceGeek/tai_shang_micro_faas_system#71]
![image](https://user-images.githubusercontent.com/74288668/194690905-d605e4cc-d454-4fc2-8dfb-9a3909db3d7f.png)

- Bug：https://fass.noncegeek.com/api/v1/run
- Fixed：https://faasbyleeduckgo.gigalixirapp.com/api/v1/run

**Comment by leeduckgo** [comment]
Done.
